"""
Prompt template and JSON output parser for the karma verification agent.

The LLM receives everything it needs to decide:
  - What the user *claims* they did (action + points + verification criteria)
  - What the image *actually shows* (AI-generated description)
  - User-supplied context (title, description, location)

It must respond with strict JSON containing exactly two keys:
  verdict  : "Approved" | "Rejected" | "Human Review"
  comment  : plain-English reason for the verdict
"""
from __future__ import annotations

import json
import re
from typing import Any

VERIFICATION_SYSTEM_PROMPT = """\
You are Chitragupt, the divine civic karma verifier for the Chitragupt app.

Your job is to decide whether a user's submitted civic action is genuine and \
deserves the claimed karma points, based solely on the image description provided.

VERDICT DEFINITIONS
-------------------
Approved     — The image description clearly and sufficiently supports the claimed action.
               All key visual evidence required by the verification criteria is present.

Rejected     — The image description does NOT support the claimed action.
               Evidence is clearly absent, mismatched, fake-looking, or contradicts the claim.

Human Review — The image description is ambiguous, partially matches, or the evidence
               is present but insufficient to decide conclusively either way.
               A human moderator should review this submission.

RULES
-----
1. Judge only on what the image description says. Do not assume or invent evidence.
2. Compare the image against the VERIFICATION CRITERIA for this specific action.
3. Location context may support or cast doubt on the claim — use it as a signal, not proof.
4. If the user's title/description directly contradicts the image — that is a red flag.
5. Be strict but fair. Ambiguity → Human Review. Clear mismatch → Rejected.

OUTPUT FORMAT — respond with ONLY valid JSON, no markdown, no extra text:
{
  "verdict": "Approved" | "Rejected" | "Human Review",
  "comment": "<concise plain-English reason, 1-3 sentences>"
}
"""

VERIFICATION_USER_TEMPLATE = """\
CLAIMED ACTION
--------------
Action ID   : {action_id}
Action      : {action_name}
Category    : {category_name} — {category_description}
Points      : {points}
Frequency   : {frequency}

VERIFICATION CRITERIA (from Chitragupt rule book)
-------------------------------------------------
{verification_details}
Verification method: {verification_method}

USER SUBMISSION
---------------
Title       : {title}
Description : {user_description}
Location    : {area}, {city}

IMAGE DESCRIPTION (generated by AI from the submitted photo)
------------------------------------------------------------
{image_description}

Now output your verdict as JSON.
"""


def build_verification_messages(
    action: dict[str, Any],
    image_description: str,
    title: str,
    user_description: str,
    area: str,
    city: str,
) -> list[dict[str, str]]:
    """Build the messages list for litellm.acompletion()."""
    verification = action.get("verification", {})
    escalation = action.get("escalation", {})

    # For negative actions there is no verification block, use escalation details
    ver_details = (
        verification.get("details")
        or escalation.get("details")
        or "No specific criteria documented."
    )
    ver_method = (
        verification.get("method")
        or ("escalation_" + str(escalation.get("level", "")))
        or "community_report"
    )

    points = action.get("points", 0)
    points_str = str(points) if isinstance(points, (int, float)) else points

    user_msg = VERIFICATION_USER_TEMPLATE.format(
        action_id=action["id"],
        action_name=action["action"],
        category_name=action.get("category_name", ""),
        category_description=action.get("category_description", ""),
        points=points_str,
        frequency=action.get("frequency", ""),
        verification_details=ver_details,
        verification_method=ver_method,
        title=title,
        user_description=user_description,
        area=area,
        city=city,
        image_description=image_description,
    )

    return [
        {"role": "system", "content": VERIFICATION_SYSTEM_PROMPT},
        {"role": "user", "content": user_msg},
    ]


# ---------------------------------------------------------------------------
# JSON output parser
# ---------------------------------------------------------------------------

_JSON_RE = re.compile(r"\{.*?\}", re.DOTALL)
_VALID_VERDICTS = {"Approved", "Rejected", "Human Review"}


def parse_verdict(raw: str) -> dict[str, str]:
    """
    Extract verdict + comment from the model's raw text response.

    Falls back to Human Review if the model output can't be parsed,
    so the API never crashes due to model output variance.
    """
    # Try direct JSON parse first
    raw = raw.strip()
    try:
        obj = json.loads(raw)
        return _validate_verdict_obj(obj)
    except (json.JSONDecodeError, ValueError):
        pass

    # Try to find a JSON object embedded in the text
    match = _JSON_RE.search(raw)
    if match:
        try:
            obj = json.loads(match.group())
            return _validate_verdict_obj(obj)
        except (json.JSONDecodeError, ValueError):
            pass

    # Complete fallback — model produced unparseable output
    return {
        "verdict": "Human Review",
        "comment": (
            "The verification model returned an unexpected response format. "
            "A human moderator should review this submission manually."
        ),
    }


def _validate_verdict_obj(obj: dict[str, Any]) -> dict[str, str]:
    verdict = obj.get("verdict", "").strip()
    comment = obj.get("comment", "").strip()

    if verdict not in _VALID_VERDICTS:
        raise ValueError(f"Invalid verdict: {verdict!r}")
    if not comment:
        raise ValueError("Empty comment")

    return {"verdict": verdict, "comment": comment}
