from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from core.config import settings
from core.exceptions import AgentError
from core.image_loader import load_image


async def describe_image(
    image_source: str,
    runner: Runner,
    session_service: InMemorySessionService,
) -> str:
    """
    Load the image, run the ADK image agent, and return the description.

    Args:
        image_source: Local path or URL of the image.
        runner:        Initialised ADK Runner instance.
        session_service: Active InMemorySessionService.

    Returns:
        Plain-text description generated by the model.

    Raises:
        ImageLoadError: Propagated from image_loader if loading fails.
        AgentError:     If the agent produces no usable output.
    """
    image_bytes, mime_type = load_image(image_source)

    session = await session_service.create_session(
        app_name="karma_backend",
        user_id="api_user",
    )

    user_message = types.Content(
        role="user",
        parts=[
            types.Part(
                inline_data=types.Blob(mime_type=mime_type, data=image_bytes)
            ),
            types.Part(text="Describe this image in detail."),
        ],
    )

    parts: list[str] = []
    async for event in runner.run_async(
        user_id="api_user",
        session_id=session.id,
        new_message=user_message,
    ):
        if event.is_final_response() and event.content:
            for part in event.content.parts:
                if hasattr(part, "text") and part.text:
                    parts.append(part.text)

    if not parts:
        raise AgentError("The model returned an empty response.")

    return "".join(parts)


def get_model_name() -> str:
    return settings.ollama_model
